### ISSUE TITLE
How to use sentence embedding in machine learning model?

### ISSUE THREAD

**Issue by ghost** [dataiku/dss-plugin-nlp-embedding#10]
Here is what I did: I uploaded a datasheet with a column that has different row of corpus. I used the DSS natural language processing to clean the text in that column. I then passed this column as an input to the sentence embedding plugin using pre-trained GLOVE word embeddings with the results shown in the new dataset. In the new datatable, I saw a column with the word vectors. 

My question is I want to perform a text clustering/classification on that column using the word vectors so I can get an analysis to determine what different categories I have in the text.
What I did was performed the DSS Kmeans algorithm against the vectorized column, but it kept giving me  list out of index errors. 

Can you give me advice on how to perform unsupervised learning to clustering the text data using sentence embedding and have it display the correct categories?

**Comment by alexcombessie** [comment]
Hi,

I have answered on the thread you have opened on the Dataiku community website (welcome!).
https://community.dataiku.com/t5/Plugins-Extending-Dataiku-DSS/Sentence-Embedding-Machine-Deep-Learning-Model/m-p/6468/highlight/false#M293

For usage questions, please continue to use the community website, so it benefits other users :)

Cheers,

Alex
