### ISSUE TITLE
Recent versions of smart open breaking Gensim 2.7

### ISSUE THREAD

**Issue by rnormgeek** [dataiku/dss-plugin-nlp-embedding#6]
Hello there,

First time posting an issue anywhere on Git so I hope I do this right !

I'm currently implementing the plugin in our DSS environment and I've stumbled upon several issues related to libraries included in the code environment created for the plugin: 

> File "/var/opt/data/dataiku/datadir/code-envs/python/plugin_dss_sentence_embedding_managed/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 24, in <module>
[11:59:18] [INFO] [dku.utils]  -     import urllib.parse
[11:59:18] [INFO] [dku.utils]  - ImportError: No module named parse

This seems to be related to this issue regarding Gensim running on 2.7 python: 
[https://github.com/RaRe-Technologies/gensim/issues/2786](https://github.com/RaRe-Technologies/gensim/issues/2786)

A workaround I found was to include in the requirements.txt the library smart-open and specify it to use an older version than 1.11.0 (1.10.1 works for me).

Cheers,
Pierre.

**Comment by du-phan** [comment]
Hi Pierre,
Good catch! Thank you for the heads up. We have updated the plugin to fix this issue  in #7. 
If you want, you can go the the plugin store page on your DSS instance, refresh it with "r l" and download the new version (1.2.1).
Have a nice day and stay healthy!
Cheers,
Du
