### ISSUE TITLE
Plugin doesn't work for 3.7

### ISSUE THREAD

**Issue by ghost** [dataiku/dss-plugin-nlp-embedding#8]
Hi Team, 

I had issues with integrating this plugin into the python code-envs environment using python 3.7 but I kept getting NoModuleErrors due to importing the abstract_model_language.py as a module. For the life of me I couldn't figure it out, I spent 12 hours trying to fix this. I tried downloading 20 GB worth of different pre-trained embeddings, re-installing the Plugin 15 times even versions with Github, I reinstalled Dataiku, and even tried in Mac, Windows-linux, and Linux machines. I must have clicked all the links on Google. 
So then I saw this comment where a code was updated to make it work for python 2.7. This made me want to install python 2.7 code envs, but it didn't work because the requirements.txt specified numpy 1.18.2 and tensorflow 1.15.2 which isn't supported. So I downgraded numpy to 1.16 and upgraded tensorflow to 2.0 and it finally worked. I thought I'd share my pain that possibly something you fixed in python 2.7 made it stop working for python 3.7. 
Please look into this issue.
Other than that I really like how the plugin works and excited to use it in ML models.

**Comment by alexcombessie** [comment]
Hello @vinhdiesal,

Thanks for your interest in this plugin and noticing this error. There is indeed an issue with Python2.7. We're looking into it right now and will push an update to the plugin store today.

We also plan to update the plugin to support Python 3.

Hope it helps,

Alex

**Comment by du-phan** [comment]
Hello,

A new version of the plugin has been updated on the store to fix the issue with python2. You can go to the store on your local instance, type "r l" to refresh it, and download the latest version (1.2.2). Thank you again for the time and interest that you put into this plugin.

Cheers,

Du
